Code_Review Trial Project
DanielAD10/code_review_trial pull request #1
Opened 2023-05-08 15:38 UTC by DanielAD10

PR Description

In this PR,

Updated inline comments in code review

Thank you so much for reviewing my code review

2023-05-08 18:31 UTC, DanielAD10 commented
Status: REQUIRED CHANGES ♻️

_Check the comments under the review._

- [ ] Kindly make sure to update your PR title and PR description by proving a well-detailed summary and title which makes your PR clean and professional and even self-explanatory. 😉

- Example of good PR Summary
![unnamed](https://user-images.githubusercontent.com/77822278/236901764-adb861b5-98fd-4c8c-85e0-f80638888b46.png)

- [ ] Kindly make sure to use the [Microverse README template](https://github.com/microverseinc/readme-template) which will help to explain your repository contents and have a clean and professional Readme. Please make sure to customize it according to your project and fill in the needed information and remember all main sections must be included except the FAQ section which is optional.
 
- [ ] Kindly make sure to add linter because of the requirements of Microverse flow.

- [ ] Kindly make sure to add text.md file and it must be presented into gitignore file and make sure that it is not represented in your repository anymore. Kindly fix that.

- In text.md file,
```
-> @@ -0,0 +1 @@
+This file should be ignored by git.
```


**Optional suggestions**

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@DanielAD10 ](https://github.com/DanielAD10) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise_**.

2023-05-08 18:51 UTC, Shisui6 requested changes
Hi @DanielAD10, 

# Requires Changes 🍀
You have done a great job so far!👏👏
Your project is almost complete. There are a few issues that you still need to work on🪲.

## Highlights
- Clear and polite comments ✅
- Comments have clear explanations why ✅


## Required Changes ♻️

- According to the project requirements, you need to have a minimum of 2 inline comments. Please update your PR to include them. You can review this [lesson](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#:~:text=Hover%20over%20the%20line%20of,comment%20field%2C%20type%20your%20comment.) as a guide

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 04:51 UTC, DanielAD10 commented on index.html
> +        </form>
- [ ] Kindly make sure to delete the blank space at line 62 and 63 to look your code look professional

2023-05-09 04:53 UTC, DanielAD10 commented on index.html
> +        <form id="survey-form">
- [ ] Kindly make sure to delete the blank space at line 14 to look your code professional

2023-05-09 04:55 UTC, DanielAD10 commented on index.html
> +            <label for="state" id=""">State: </label>
- [ ] Kindly make sure to delete the blank space at line 32, 39 and 46 to look your code professional

2023-05-09 04:58 UTC, DanielAD10 commented on index.html
> +        <form id="survey-form">
- [ ] According to the code flow of Microverse, kindly make sure to use `class` (at `h1` tag, `p` tag and `form` tag) except using `id`

2023-05-09 04:59 UTC, DanielAD10 commented on style.css
> +.container {
- [ ] Kindly make sure to add a new line after the `}` to look your css code professional

2023-05-09 05:00 UTC, DanielAD10 commented on style.css
> +button {
- [ ] Kindly make sure to add a new line after the `}` to look your css code professional

2023-05-09 05:00 UTC, DanielAD10 commented on style.css
> +}
- [ ] Kindly make sure to add a new line after the` } `to look your css code professional

2023-05-09 05:10 UTC, DanielAD10 reviewed
Changes Required ♻️ 

Please make sure to check the comments below the code and do all the required changes.

Submit the re-review after you are done.

If you have any questions, just mention my name @DanielAD10 to reach out directly to me.

Thanks, 😁

2023-05-09 05:21 UTC, DanielAD10 reviewed
Changes Required ♻️

Please make sure to check the comments below the code and do all the required changes.

Submit the re-review after you are done.

If you have any questions, just mention my name @DanielAD10 to reach out directly to me.

Thanks, 😁

2023-05-09 05:21 UTC, DanielAD10 commented on index.html
> +        <form id="survey-form">
- [ ]  Kindly make sure to delete the blank space at line 14 to look your code professional

2023-05-09 05:21 UTC, DanielAD10 commented on index.html
> +        <form id="survey-form">
- [ ] According to the code flow of Microverse, kindly make sure to use `class` (at `h1` tag,` p` tag and` form` tag) except using` id`

2023-05-09 05:21 UTC, DanielAD10 commented on index.html
> +            <label for="state" id=""">State: </label>
- [ ] Kindly make sure to delete the blank space at line 32, 39 and 46 to look your code professional

2023-05-09 05:21 UTC, DanielAD10 commented on index.html
> +        </form>
- [ ] Kindly make sure to delete the blank space at line 62 and 63 to look your code look professional

2023-05-09 05:21 UTC, DanielAD10 commented on index.html
> +</body>
- [ ] Kindly make sure to delete the blank space at line 66 to look your code look professional

2023-05-09 05:21 UTC, DanielAD10 commented on style.css
> +.container {
- [ ]  Kindly make sure to add a new line after the` }` to look your css code professional

2023-05-09 05:21 UTC, DanielAD10 commented on style.css
> +button {
- [ ] Kindly make sure to add a new line after the` }` to look your css code professional

2023-05-09 05:21 UTC, DanielAD10 commented on style.css
> +}
- [ ]  Kindly make sure to add a new line after the `}` to look your css code professional

2023-05-09 05:28 UTC, usorfaitheloho approved these changes
Hi @DanielAD10 , 
# STATUS: APPROVED! 🥇 💯 
- [x] Used polite inline comment, Keep it up!!
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 05:35 UTC, merged